language: node_js
node_js:
  - "10"

services:
  - docker

before_install:
  # Enable user namespace cloning
  - "sysctl kernel.unprivileged_userns_clone=1"
  # Launch XVFB
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - node --version
  - npm --version
  - npx --version
  - npm install -g codecov
before_script:
  - ng build --prod
  - ng build --prod --single-bundle
script:
  - npm run e2e
  - codecov
after_script:
  - echo 'Ende'
